<x-layouts::app :title="__('Facilities')">
    <div class="app-page">
        @if (session('status')) <div class="app-alert-success">{{ session('status') }}</div> @endif
        @if (session('activation_code_notice') && session('activation_code') && session('activation_code_expires_at') && now()->isBefore(\Illuminate\Support\Carbon::parse(session('activation_code_expires_at'))))
            <div class="app-alert-success flex flex-wrap items-center justify-between gap-3" x-data="{ visible: true, copied: false, code: @js(session('activation_code')), init() { setTimeout(() => this.visible = false, 8000); }, fallbackCopy() { const input = document.createElement('textarea'); input.value = this.code; input.setAttribute('readonly', ''); input.style.position = 'fixed'; input.style.opacity = '0'; document.body.appendChild(input); input.select(); const copied = document.execCommand('copy'); input.remove(); if (! copied) throw new Error('Clipboard fallback failed'); }, async copy() { try { if (navigator.clipboard?.writeText) { try { await navigator.clipboard.writeText(this.code); } catch (error) { this.fallbackCopy(); } } else { this.fallbackCopy(); } this.copied = true; setTimeout(() => this.copied = false, 1500); } catch (error) { console.warn('Could not copy activation code', error); } } }" x-show="visible">
                <div class="min-w-0"><p class="text-xs font-medium uppercase tracking-wide opacity-75">Activation code</p><code class="mt-1 block break-all text-sm font-semibold tracking-wide">{{ session('activation_code') }}</code></div>
                <div class="flex shrink-0 items-center gap-2"><button type="button" class="app-button-secondary inline-flex items-center gap-2 !px-3 !py-1.5 !text-xs" @click="copy()"><flux:icon.document-duplicate x-show="!copied" variant="outline" class="size-4" /><flux:icon.check x-show="copied" variant="solid" class="size-4 text-green-500" /><span x-text="copied ? 'Copied' : 'Copy code'"></span></button><button type="button" class="rounded-md p-1 text-lg leading-none opacity-70 hover:opacity-100" title="Dismiss" aria-label="Dismiss activation code notice" @click="visible = false">&times;</button></div>
            </div>
        @endif
        <div class="page-heading"><div><p class="eyebrow">CENTRAL</p><h1 class="page-title">Facilities</h1><p class="page-subtitle">Register facilities and issue one-time connection codes.</p></div></div>
        <section class="app-card p-5"><form method="POST" action="{{ route('central.facilities.store') }}" class="grid gap-4 md:grid-cols-3">@csrf <flux:input name="code" label="Facility code" required /> <flux:input name="name" label="Facility name" required /> <div class="flex items-center justify-center"><flux:button class="w-full" variant="primary" type="submit">Register facility</flux:button></div></form></section>
        <section class="app-card mt-6 overflow-x-auto"><table class="app-table"><thead><tr><th>Code</th><th>Name</th><th>Active connections</th><th>Actions</th></tr></thead><tbody>@forelse ($facilities as $facility)<tr class="app-table-row"><td>{{ $facility->code }}</td><td>{{ $facility->name }}</td><td><span class="{{ $facility->active_connections_count ? 'text-emerald-600 dark:text-emerald-400' : 'text-zinc-500' }}">{{ $facility->active_connections_count ? 'Connected ('.$facility->active_connections_count.')' : 'Not connected' }}</span></td><td><div class="flex flex-wrap items-center gap-2"><form method="POST" action="{{ route('central.facilities.issue-code', $facility) }}">@csrf <button class="app-button-secondary inline-flex items-center gap-2 !px-3 !py-1.5 !text-xs"><flux:icon.key class="size-4" />Generate activation code</button></form>@if (session('activation_code') && session('activation_code_expires_at') && now()->isBefore(\Illuminate\Support\Carbon::parse(session('activation_code_expires_at'))) && session('activation_code_facility_id') === $facility->id)<div x-data="{ copied: false, code: @js(session('activation_code')), fallbackCopy() { const input = document.createElement('textarea'); input.value = this.code; input.setAttribute('readonly', ''); input.style.position = 'fixed'; input.style.opacity = '0'; document.body.appendChild(input); input.select(); const copied = document.execCommand('copy'); input.remove(); if (! copied) throw new Error('Clipboard fallback failed'); }, async copy() { try { if (navigator.clipboard?.writeText) { try { await navigator.clipboard.writeText(this.code); } catch (error) { this.fallbackCopy(); } } else { this.fallbackCopy(); } this.copied = true; setTimeout(() => this.copied = false, 1500); } catch (error) { console.warn('Could not copy activation code', error); } } }"><button type="button" class="app-button-secondary inline-flex items-center justify-center !px-2 !py-1.5" title="Copy activation code" aria-label="Copy activation code" @click="copy()"><flux:icon.document-duplicate x-show="!copied" variant="outline" class="size-4" /><flux:icon.check x-show="copied" variant="solid" class="size-4 text-green-500" /></button></div>@endif @if ($facility->active_connections_count)<form method="POST" action="{{ route('central.facilities.revoke-connections', $facility) }}" onsubmit="return confirm('Revoke all active connections for this facility? The local server will need a new activation code to reconnect.');">@csrf <button class="app-button-secondary inline-flex items-center gap-2 !border-red-300 !text-red-600 hover:!bg-red-50 dark:!border-red-800 dark:!text-red-400 dark:hover:!bg-red-950 !px-3 !py-1.5 !text-xs"><flux:icon.no-symbol class="size-4" />Revoke connection</button></form>@endif</div></td></tr>@empty<tr><td colspan="4" class="px-4 py-8 text-center text-zinc-500">No facilities registered.</td></tr>@endforelse</tbody></table></section>
    </div>
</x-layouts::app>
