<x-layouts::app :title="__('Facilities')">
    <div class="app-page">
        @if (session('status')) <div class="app-alert-success">{{ session('status') }}</div> @endif
        @if (session('activation_code_notice') && session('activation_code') && session('activation_code_expires_at') && now()->isBefore(\Illuminate\Support\Carbon::parse(session('activation_code_expires_at'))))
            <div class="app-alert-success flex flex-wrap items-center justify-between gap-3" x-data="{ visible: true, copied: false, code: @js(session('activation_code')), init() { setTimeout(() => this.visible = false, 8000); }, fallbackCopy() { const input = document.createElement('textarea'); input.value = this.code; input.setAttribute('readonly', ''); input.style.position = 'fixed'; input.style.opacity = '0'; document.body.appendChild(input); input.select(); const copied = document.execCommand('copy'); input.remove(); if (! copied) throw new Error('Clipboard fallback failed'); }, async copy() { try { if (navigator.clipboard?.writeText) { try { await navigator.clipboard.writeText(this.code); } catch (error) { this.fallbackCopy(); } } else { this.fallbackCopy(); } this.copied = true; setTimeout(() => this.copied = false, 1500); } catch (error) { console.warn('Could not copy activation code', error); } } }" x-show="visible">
                <div class="min-w-0"><p class="text-xs font-medium uppercase tracking-wide opacity-75">Activation code</p><code class="mt-1 block break-all text-sm font-semibold tracking-wide">{{ session('activation_code') }}</code></div>
                <div class="flex shrink-0 items-center gap-2"><button type="button" class="app-button-secondary inline-flex items-center gap-2 !px-3 !py-1.5 !text-xs" @click="copy()"><flux:icon.document-duplicate x-show="!copied" variant="outline" class="size-4" /><flux:icon.check x-show="copied" variant="solid" class="size-4 text-green-500" /><span x-text="copied ? 'Copied' : 'Copy code'"></span></button><button type="button" class="rounded-md p-1 text-lg leading-none opacity-70 hover:opacity-100" title="Dismiss" aria-label="Dismiss activation code notice" @click="visible = false">&times;</button></div>
            </div>
        @endif
        <div class="page-heading"><div><p class="eyebrow">CENTRAL</p><h1 class="page-title">Connected facilities</h1><p class="page-subtitle">Manage facility connections and issue one-time activation codes by location.</p></div></div>
        @if (! $fromGroupManagement)
        <form method="GET" class="app-card relative z-30 mt-6 grid gap-4 overflow-visible p-5 md:grid-cols-4"> <x-searchable-location-filter label="Region" name="region" :options="$regions->pluck('name', 'id')" :value="$filters['region'] ?? null" /> <x-searchable-location-filter label="Province" name="province" :options="$provinces->pluck('name', 'id')" :value="$filters['province'] ?? null" :disabled="blank($filters['region'] ?? null)" /> <x-searchable-location-filter label="Municipality" name="municipality" :options="$municipalities->pluck('name', 'id')" :value="$filters['municipality'] ?? null" :disabled="blank($filters['region'] ?? null) || blank($filters['province'] ?? null)" /> <x-searchable-location-filter label="Barangay" name="barangay" :options="$barangays->pluck('name', 'id')" :value="$filters['barangay'] ?? null" :disabled="blank($filters['region'] ?? null) || blank($filters['province'] ?? null) || blank($filters['municipality'] ?? null)" /> <div class="md:col-span-4"><button class="app-button-primary">Apply filters</button><a href="{{ route('central.facilities.index') }}" class="app-button-secondary ml-2">Clear</a></div></form>
        @endif
        <section class="app-card mt-6 grid gap-4 p-5" x-data="{ selected: @js((string) ($filters['barangay'] ?? '')), code: '', name: '', locations: @js($facilityBarangays->map(fn ($barangay) => ['id' => (string) $barangay->id, 'code' => 'RHU-'.strtoupper(str_replace(' ', '-', $barangay->name)), 'name' => $barangay->name.' Clinic'])->values()), applySuggestion() { const location = this.locations.find(item => item.id === this.selected); this.code = location?.code ?? ''; this.name = location?.name ?? ''; } }" x-init="applySuggestion()"><div><h2 class="app-card-title">Add facility</h2><p class="mt-1 text-sm text-zinc-500">Select Region, Province, and Municipality first. Suggested code and name are generated from the selected Barangay and remain editable.</p></div><form method="POST" action="{{ route('central.facilities.store') }}" class="grid gap-4 md:grid-cols-4">@csrf <label class="grid gap-2 text-sm"><span class="font-medium text-slate-800 dark:text-zinc-100">Barangay</span><select name="barangay_id" x-model="selected" @change="applySuggestion()" class="app-input" @disabled($facilityBarangays->isEmpty()) required><option value="">{{ $facilityBarangays->isEmpty() ? 'Select municipality first' : 'Select barangay' }}</option>@foreach($facilityBarangays as $barangay)<option value="{{ $barangay->id }}">{{ $barangay->name }} ({{ $barangay->municipalityRelation?->name }})</option>@endforeach</select></label><label class="grid gap-2 text-sm"><span class="font-medium text-slate-800 dark:text-zinc-100">Facility code</span><input name="code" x-model="code" class="app-input" placeholder="Suggested code" @disabled($facilityBarangays->isEmpty()) /></label><label class="grid gap-2 text-sm"><span class="font-medium text-slate-800 dark:text-zinc-100">Facility name</span><input name="name" x-model="name" class="app-input" placeholder="Suggested name" @disabled($facilityBarangays->isEmpty()) /></label><div class="flex items-end"><button class="app-button-primary w-full" @disabled($facilityBarangays->isEmpty())>Add facility</button></div></form></section>
        <section class="app-card mt-6 overflow-x-auto"><table class="app-table"><thead><tr><th>Location</th><th>Code</th><th>Facility</th><th>Connections</th><th>Actions</th></tr></thead><tbody>@forelse ($facilities as $facility)<tr class="app-table-row"><td>@if ($facility->barangay){{ $facility->barangay->municipalityRelation?->province?->region?->name }} · {{ $facility->barangay->municipalityRelation?->name }} · {{ $facility->barangay->name }}@else<form method="POST" action="{{ route('central.facilities.update', $facility) }}" class="flex items-center gap-2">@csrf @method('PATCH')<select name="barangay_id" class="app-input !py-1.5 text-xs" required><option value="">Assign barangay</option>@foreach($barangays as $barangay)<option value="{{ $barangay->id }}">{{ $barangay->name }} ({{ $barangay->municipalityRelation?->name }})</option>@endforeach</select><button class="app-button-secondary !px-2 !py-1.5 !text-xs">Save</button></form>@endif</td><td>{{ $facility->code }}</td><td>{{ $facility->name }}</td><td><span class="{{ $facility->active_connections_count ? 'text-emerald-600 dark:text-emerald-400' : 'text-zinc-500' }}">{{ $facility->active_connections_count ? 'Connected ('.$facility->active_connections_count.')' : 'Not connected' }}</span></td><td><div class="flex flex-wrap items-center gap-2"><form method="POST" action="{{ route('central.facilities.issue-code', $facility) }}">@csrf <button class="app-button-secondary inline-flex items-center gap-2 !px-3 !py-1.5 !text-xs"><flux:icon.key class="size-4" />Generate code</button></form>@if ($facility->active_connections_count)<form method="POST" action="{{ route('central.facilities.revoke-connections', $facility) }}" onsubmit="return confirm('Revoke all active connections for this facility? The local server will need a new activation code to reconnect.');">@csrf <button class="app-button-secondary !border-red-300 !text-red-600 !px-3 !py-1.5 !text-xs">Revoke</button></form>@endif</div></td></tr>@empty<tr><td colspan="5" class="px-4 py-8 text-center text-zinc-500">No facilities registered for this location.</td></tr>@endforelse</tbody></table></section>
    </div>
</x-layouts::app>
