<?php

use App\Http\Controllers\AdminReportController;
use App\Http\Controllers\AdverseEventReportController;
use App\Http\Controllers\Api\OfflineVaccinationSyncController;
use App\Http\Controllers\Api\ParentChildController;
use App\Http\Controllers\ChildParentController;
use App\Http\Controllers\ChildProfileController;
use App\Http\Controllers\ChildTimelinePdfController;
use App\Http\Controllers\ClinicAnnouncementController;
use App\Http\Controllers\GroupController;
use App\Http\Controllers\ManualSyncController;
use App\Http\Controllers\MunicipalAdminController;
use App\Http\Controllers\LocationController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\NurseController;
use App\Http\Controllers\VaccinationRecordController;
use App\Http\Controllers\VaccineCardController;
use App\Http\Controllers\VaccineInventoryController;
use App\Http\Controllers\VaccineScheduleController;
use App\Livewire\AefiReportsPage;
use App\Livewire\AnnouncementsPage;
use App\Livewire\AuditLogsPage;
use App\Livewire\ChildCreatePage;
use App\Livewire\ChildEditPage;
use App\Livewire\ChildrenIndexPage;
use App\Livewire\ChildShowPage;
use App\Livewire\ChildTimelinePage;
use App\Livewire\DashboardPage;
use App\Livewire\DefaulterPage;
use App\Livewire\DuplicateChildrenPage;
use App\Livewire\NotificationsPage;
use App\Livewire\NursesPage;
use App\Livewire\ReportsPage;
use App\Livewire\SyncDataPage;
use App\Livewire\VaccineScheduleFormPage;
use App\Livewire\VaccineSchedulesPage;
use App\Livewire\VerificationQueuePage;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    if (auth()->check()) {
        return redirect()->route('dashboard');
    }

    return view('welcome');
})->name('home');
Route::get('vaccine-cards/{token}', [VaccineCardController::class, 'validateToken'])->name('vaccine-cards.validate');

Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('dashboard', DashboardPage::class)->name('dashboard');
    Route::get('children', ChildrenIndexPage::class)->name('children.index');
    Route::get('children/create', ChildCreatePage::class)->name('children.create');
    Route::post('children', [ChildProfileController::class, 'store'])->name('children.store');
    Route::get('children/{child}', ChildShowPage::class)->name('children.show');
    Route::get('children/{child}/edit', ChildEditPage::class)->name('children.edit');
    Route::put('children/{child}', [ChildProfileController::class, 'update'])->name('children.update');
    Route::post('children/{child}/transfer', [ChildProfileController::class, 'transfer'])->name('children.transfer');
    Route::get('children/{child}/timeline', ChildTimelinePage::class)->name('children.timeline');
    Route::get('children/{child}/timeline/pdf', ChildTimelinePdfController::class)->name('children.timeline.pdf');
    Route::get('children/{child}/timeline/csv', [ChildTimelinePdfController::class, 'csv'])->name('children.timeline.csv');
    Route::get('children/{child}/card', [VaccineCardController::class, 'show'])->name('children.card');
    Route::get('children/{child}/card/pdf', [VaccineCardController::class, 'pdf'])->name('children.card.pdf');
    Route::post('children/{child}/parents', [ChildParentController::class, 'store'])->name('children.parents.store');
    Route::post('children/{child}/parents/{parent}/setup-link', [ChildParentController::class, 'resendSetupLink'])->name('children.parents.setup-link');
    Route::delete('children/{child}/parents/{parent}', [ChildParentController::class, 'destroy'])->name('children.parents.destroy');
    Route::post('children/{child}/vaccinations', [VaccinationRecordController::class, 'store'])->name('children.vaccinations.store');
    Route::put('vaccinations/{record}', [VaccinationRecordController::class, 'update'])->name('vaccinations.update');
    Route::get('vaccinations/{record}/proofs/{proofIndex}', [VaccinationRecordController::class, 'showProof'])->name('vaccinations.proofs.show');
    Route::post('vaccinations/{record}/verify', [VaccinationRecordController::class, 'verify'])->name('vaccinations.verify');
    Route::post('vaccinations/{record}/reject', [VaccinationRecordController::class, 'reject'])->name('vaccinations.reject');
    Route::get('nurses', NursesPage::class)->name('nurses.index');
    Route::get('municipal-admins', NursesPage::class)->name('municipal-admins.index');
    Route::post('nurses', [NurseController::class, 'store'])->name('nurses.store');
    Route::post('nurses/{nurse}/setup-link', [NurseController::class, 'resendSetupLink'])->name('nurses.setup-link');
    Route::post('nurses/{nurse}/toggle', [NurseController::class, 'toggle'])->name('nurses.toggle');
    Route::post('nurses/{nurse}/restore', [NurseController::class, 'restore'])->name('nurses.restore');
    Route::delete('nurses/{nurse}', [NurseController::class, 'destroy'])->name('nurses.destroy');
    Route::get('groups', [GroupController::class, 'index'])->name('groups.index');
    Route::post('municipal-admins', [MunicipalAdminController::class, 'store'])->name('municipal-admins.store');
    Route::post('users/{user}/municipality', [MunicipalAdminController::class, 'assign'])->name('users.municipality.assign');
    Route::post('locations/regions', [LocationController::class, 'region'])->name('locations.regions.store');
    Route::post('locations/provinces', [LocationController::class, 'province'])->name('locations.provinces.store');
    Route::post('locations/municipalities', [LocationController::class, 'municipality'])->name('locations.municipalities.store');
    Route::post('locations/barangays', [LocationController::class, 'barangay'])->name('locations.barangays.store');
    Route::post('locations/municipalities/{municipality}/assign-user', [LocationController::class, 'assignMunicipality'])->name('locations.municipalities.assign-user');
    Route::post('locations/barangays/{barangay}/assign-user', [LocationController::class, 'assignBarangay'])->name('locations.barangays.assign-user');
    Route::post('locations/municipalities/{municipality}/users', [LocationController::class, 'addToMunicipality'])->name('locations.municipalities.users.store');
    Route::post('locations/barangays/{barangay}/users', [LocationController::class, 'addToBarangay'])->name('locations.barangays.users.store');
    Route::post('locations/users/{user}/remove', [LocationController::class, 'removeUser'])->name('locations.users.remove');
    Route::post('locations/users/{user}/reassign', [LocationController::class, 'reassignUser'])->name('locations.users.reassign');
    Route::get('reports', ReportsPage::class)->name('reports.index');
    Route::get('audit-logs', AuditLogsPage::class)->name('audit-logs.index');
    Route::get('reports/pdf', [AdminReportController::class, 'pdf'])->name('reports.pdf');
    Route::get('reports/csv', [AdminReportController::class, 'csv'])->name('reports.csv');
    Route::get('sync', SyncDataPage::class)->name('sync.index');
    Route::post('sync/manual', [ManualSyncController::class, 'store'])->name('sync.manual');
    Route::get('announcements', AnnouncementsPage::class)->name('announcements.index');
    Route::get('notifications', NotificationsPage::class)->name('notifications.index');
    Route::get('notifications/{notification}/read', [NotificationController::class, 'read'])->name('notifications.read');
    Route::post('announcements', [ClinicAnnouncementController::class, 'store'])->name('announcements.store');
    Route::post('announcements/{announcement}/toggle', [ClinicAnnouncementController::class, 'toggle'])->name('announcements.toggle');
    Route::delete('announcements/{announcement}', [ClinicAnnouncementController::class, 'destroy'])->name('announcements.destroy');
    Route::get('verification-queue', VerificationQueuePage::class)->name('verification-queue.index');
    Route::get('defaulters', DefaulterPage::class)->name('defaulters.index');
    Route::get('duplicates', DuplicateChildrenPage::class)->name('duplicates.index');
    Route::get('aefi-reports', AefiReportsPage::class)->name('aefi-reports.index');
    Route::get('aefi-reports/csv', [AdverseEventReportController::class, 'csv'])->name('aefi-reports.csv');
    Route::post('children/{child}/aefi-reports', [AdverseEventReportController::class, 'store'])->name('children.aefi-reports.store');
    Route::get('vaccine-schedules', VaccineSchedulesPage::class)->name('vaccine-schedules.index');
    Route::get('vaccine-inventory', [VaccineInventoryController::class, 'index'])->name('vaccine-inventory.index');
    Route::get('vaccine-inventory/report', [VaccineInventoryController::class, 'report'])->name('vaccine-inventory.report');
    Route::get('vaccine-inventory/csv', [VaccineInventoryController::class, 'csv'])->name('vaccine-inventory.csv');
    Route::get('vaccine-inventory/create', [VaccineInventoryController::class, 'create'])->name('vaccine-inventory.create');
    Route::post('vaccine-inventory', [VaccineInventoryController::class, 'store'])->name('vaccine-inventory.store');
    Route::delete('vaccine-inventory/{inventoryItem}', [VaccineInventoryController::class, 'destroy'])->name('vaccine-inventory.destroy');
    Route::get('vaccine-schedules/create', VaccineScheduleFormPage::class)->name('vaccine-schedules.create');
    Route::post('vaccine-schedules', [VaccineScheduleController::class, 'store'])->name('vaccine-schedules.store');
    Route::get('vaccine-schedules/{vaccineSchedule}/edit', VaccineScheduleFormPage::class)->name('vaccine-schedules.edit');
    Route::put('vaccine-schedules/{vaccineSchedule}', [VaccineScheduleController::class, 'update'])->name('vaccine-schedules.update');
    Route::post('vaccine-schedules/{vaccineSchedule}/toggle', [VaccineScheduleController::class, 'toggle'])->name('vaccine-schedules.toggle');
    Route::post('vaccine-types/{vaccineType}/toggle', [VaccineScheduleController::class, 'toggleVaccine'])->name('vaccine-types.toggle');
    Route::post('vaccine-schedule-versions', [VaccineScheduleController::class, 'storeVersion'])->name('vaccine-schedule-versions.store');
    Route::post('vaccine-schedule-versions/{vaccineScheduleVersion}/activate', [VaccineScheduleController::class, 'activateVersion'])->name('vaccine-schedule-versions.activate');

    Route::prefix('api/parent')->name('api.parent.')->group(function () {
        Route::get('children', [ParentChildController::class, 'index'])->name('children.index');
        Route::get('children/{child}/vaccinations', [ParentChildController::class, 'vaccinations'])->name('children.vaccinations');
        Route::post('children/{child}/vaccinations', [ParentChildController::class, 'storeVaccination'])->name('children.vaccinations.store');
        Route::post('children/{child}/offline-sync', [OfflineVaccinationSyncController::class, 'store'])->name('children.offline-sync');
        Route::get('vaccines', [ParentChildController::class, 'vaccines'])->name('vaccines.index');
    });
});

require __DIR__.'/settings.php';
